FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

# Copy the built Spring Boot JAR from target/ and name it app.jar
COPY target/*.jar app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]

FROM maven:3.9.5-openjdk-21
COPY . .
RUN mvn clean package -DskipTests

FROM openjdk:21-jdk-slim
COPY --from=builder /target/AaharExpress_B-0.0.1-SNAPSHOT.jar AaharExpress_B.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","AaharExpress_B.jar"]
